services:
  chromadb:
    image: chromadb/chroma
    volumes:
      - ./database:/chroma/chroma

  backend:
    image: wuihee/trial-search-backend:latest

  frontend:
    image: wuihee/trial-search-frontend:latest
    volumes:
      - ./ssl:/etc/ssl
    ports:
      - 80:80
      - 443:443
