services:
  chromadb:
    image: chromadb/chroma
    volumes:
      - ./database:/chroma/chroma

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    volumes:
      - ./ssl:/etc/ssl
    ports:
      - 80:80
      - 443:443
