version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8001:8001

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80

  chromadb:
    image: chromadb/chroma
    volumes:
      - chroma-data:/chroma/chroma
    ports:
      - 8000:8000

volumes:
  chroma-data:
