services:
  chromadb:
    image: chromadb/chroma
    volumes:
      - chroma-data:/chroma/chroma
    ports:
      - 8000:8000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8001:8001

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ssl:/etc/ssl
    ports:
      - 80:80
      - 443:443

volumes:
  chroma-data:
  ssl:
