services:
  chromadb:
    image: chromadb/chroma
    volumes:
      - ./database:/chroma/chroma

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8001:8001

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 5173:5173
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /app/src
          ignore:
            - node_modules
