services:
  chromadb:
    image: chromadb/chroma
    volumes:
      - chroma-data:/chroma/chroma
    ports:
      - 8000:8000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    depends_on:
      - chromadb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - backend

volumes:
  chroma-data:
