services:
  chromadb:
    image: chromadb/chroma
    volumes:
      - ./database:/chroma/chroma

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    volumes:
      - dist:/app/dist

  nginx:
    image: nginx:1.27.1-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ssl:/etc/ssl
    ports:
      - 80:80
      - 443:443

volumes:
  ssl:
  dist:
