name: Publish Images
on: [workflow_dispatch]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ${{ env.REGISTRY }} Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Frontend
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: "{{defaultContext}}:frontend"
          file: Dockerfile.prod
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/trial-search-frontend:latest

      - name: Build and Push Backend
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: "{{defaultContext}}:backend"
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/trial-search-backend:latest
